spring:
   application:
      name: gcpjwtservice
conjur:
   audience: conjur/cyberark/host/projects
   authnpath: gcpauthn/path
   projectpath: secrets/path/projects
   application:
      url: "http://localhost:8000"
gcp:
   service:
      name: my-gcp-service
   stage:
      name: developer
   project:
      id: gcp123456